### ISSUE TITLE
nginx lacks permissions to access certs

### ISSUE THREAD

**Issue by sivertism** [ibizaman/selfhostblocks#134]
Certs are created with read-only group permissions for acme:acme. However, nginx is not part of the acme group, so it does not have access.

Fixed this temporarily on my server by adding nginx to the acme group, but maybe it makes more sense to add a new group?

**Comment by ibizaman** [comment]
Indeed, there's a discrepancy between the permissions of the certificate generated by the self-signed provider and the Let's Encrypt one. The self-signed creates a certificate owned by `root` which has permission 444. Before the latest update to the SSL block, I was setting up the permissions for nginx like so:

```nix
users.users.${config.services.nginx.user} = {
  isSystemUser = true;
  group = "nginx";
  extraGroups = [ config.security.acme.defaults.group ];
};
users.groups.nginx = {};
```
I'm pondering what's the best way to fix this.

**Comment by sivertism** [comment]
Is it all right to have permissive file permissions on certs? Maybe I'm missing something, but it seems like common practice is to do very strict permissions, e.g. [this SO answer](https://superuser.com/a/556496).

**Comment by sivertism** [comment]
Oh, I see, I misunderstood you then. So what you're suggesting is something like
1. acme generates certs (when needed)
2. acme transfers ownership to whomever needs the certs (for now nginx, but could be any block compliant with the SSL contract). This would be like `chmod 400 <certs> && chown nginx:nginx <certs>` (can we change owner after chmod 400?)

So then there are (at least) two issues to be solved -- one is finding the new owner, and the other is to let acme know when to fetch new certs, given that it can't read them anymore?

**Comment by ibizaman** [comment]
Yes, that's what I had in mind :+1: 

About your concerns:
- Finding the new owner. The bare minimum IMO is to add an "owner" option when creating the certificate and you must give it manually.
  It would be even better if nginx could set that when you fill in its `ssl` option. But that would require for the Nginx block to be better than it is so let's leave that for later. 
- The [security.acme.certs.\<name\>.postRun](https://search.nixos.org/options?channel=23.11&show=security.acme.certs.%3Cname%3E.postRun&from=0&size=50&sort=relevance&type=packages&query=security.acme) option is nice because it actually runs as root, so the order of `chmod` and `chown` doesn't matter.
- For Let's Encrypt, we use the nixpkgs provided service and that one renews certs already. For self-signed, indeed we would need a systemd timer that updates them every month.

One more thing I just thought of :sweat_smile: :

- Upon renewal, we would need to reload services that depends on it. Something like what the [nixpkgs provided acme service](https://github.com/NixOS/nixpkgs/blob/1b64fc1287991a9cce717a01c1973ef86cb1af0b/nixos/modules/security/acme/default.nix#L385-L387) does.
